export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const  ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETO = 'DEFINIR_PROJETO'

export const NOTIFICAR = 'NOTIFICAR'



export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONA_TAREFAS = 'ADICIONA_TAREFAS'
export const ALTERA_TAREFA = 'ALTERA_TAREFA'
